project_id = "zwytwtwnfouazkuyygkm"

[functions.zapier-lead-webhook]
verify_jwt = false

[functions.verify-admin-password]
verify_jwt = false

[functions.meta-sync]
verify_jwt = false

[functions.check-triggers]
verify_jwt = false
